### transaction test with previous populated dabase

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "372b5874-252a-48ac-80d6-d9c4c2f10114",
  "account_id_to": "6b76d113-257a-4942-93fd-d97c42491dac",
  "amount": 100
}


### 1 create client

POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Uiratan",
  "email": "u@u.com"
}

### 2 - create account - change client_id with request 1 response

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": ""
}


### 5 - change account_id_to with request 2 response

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "372b5874-252a-48ac-80d6-d9c4c2f10114",
  "account_id_to": "",
  "amount": 100
}

