POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Uiratan",
  "email": "u@u.com"
}

###

POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Liana",
  "email": "l@l.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "5bce7c5e-2f6a-4403-a165-2a2dec15baa8"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "33396f9d-f2a6-4d91-a453-a3b8980fdcf1",
  "account_id_to": "24a9de31-cc13-4380-a20b-9696bb961052",
  "amount": 1
}